[package]
name = "cruid"
version = "0.0.0"
edition = "2021"

[dependencies]
aes = "0.8"
base16ct = "0.1"

# optional dependencies
uuid = { version = "1", optional = true, default-features = false }

[features]
std = []